FROM python:3.13.11-slim

# copying the bin file of the uv from the uv base docker image
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

#RUN pip install pandas pyarrow


WORKDIR /app

ENV PATH="/app/.venv/bin:$PATH"

COPY "pyproject.toml" "uv.lock" ".python-version" ./

RUN uv sync --locked

COPY ingest_data.py ingest_data.py

ENTRYPOINT [ "python" , "ingest_data.py" ]  

